---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.2

inputs:
  - name: dp-deployer

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-deployer/ci/scripts/build.sh
