---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.7

inputs:
  - name: dp-deployer
    path: go/src/github.com/ONSdigital/dp-deployer

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-deployer/ci/scripts/build.sh
